### ISSUE TITLE
Add support for Vega-Lite

### ISSUE THREAD

**Issue by domoritz** [GCheung55/ember-vega#10]
It would be great if you could support Vega-Lite as well.

**Comment by AhemedHan** [comment]
any updates regarding the support for vega lite

**Comment by GCheung55** [comment]
@AhemedHan While support for Vega-lite isn't included in this addon, it's pretty simple to use it... with the inclusion of `ember-auto-import`.

I haven't tried this, but I think it would work:

1. Install `vega-lite` as a dependency in your app.
2. Import vega-lite and have it compile your vega-lite spec to output a vega spec.

// Assuming this is in a component
```
import Component from '@ember/component';
import { computed } from '@ember/object';
import { compile } from 'vega-lite';

export default Component.extend({
    spec: computed(function() {
        const vegaLiteSpec = { /* ... */ };
        return compile(vegaLiteSpec).spec;
    })
})
```

Corresponding template
```
{{vega-vis spec=spec}}
```

**Comment by domoritz** [comment]
Nice. Maybe you could include this code in the library.

**Comment by GCheung55** [comment]
I'm leaving the inclusion of vega-lite up to the consumer of this addon so the addon doesn't increase in size by having a vega-lite dependency. I've added docs on how to add/use vega-lite along with this addon.
