### ISSUE TITLE
is this branch production ready?

### ISSUE THREAD

**Issue by TheLooseCannon** [GCheung55/ember-vega#12]

**Comment by GCheung55** [comment]
Are you referring to the update-vega-5 branch? If so, yes, however I need to make sure to document the usage of ember-auto-import and ember-d3 before merging into master and publishing a new version.

**Comment by AhemedHan** [comment]
```
dataSource: computed(function() {
    return emberArray([
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
    ]);
}),

data: computed('dataSource.{[],@each.amount}', function () {
    const dataSource = get(this, 'dataSource');
    return {
        table: dataSource.map((datum) => {
            // return a copy because Vega Vis will mutate the dataset.
            return {
                ...datum
            };
        })
    };
}),
```

[(https://gcheung55.github.io/ember-vega/latest/docs/components/vega-vis)]

im looking to have a vega chart with a constant stream of data. could you help me with this.
i want the chart to monitor the value from the model and show accordingly. im using ember octane and ember orbit for the data part

**Comment by AhemedHan** [comment]
im trying to bind a tracked variable to the charts data, which does get updated alright but this doesn't change the chart

  
```@tracked
  model!: any;

get chartData() {
    const data = this.model.data;
    return {
      table: data.map((datum: any) => {
        return {
          ...datum
        };
      })
    };
  }```


any suggestions?

**Comment by GCheung55** [comment]
@AhemedHan for streaming, you’ll want to pass return an object containing a `changeset` that only inserts new data.

Take a look at this action: https://github.com/GCheung55/ember-vega/blob/master/tests/dummy/app/components/vega-vis-demo-data-function.js

As for tracked properties not updating the chart, I’m not familiar with tracking changes in Glimmer components but you may need to add the `@tracked` annotation above the `model` property definition - I cant tell from your code snippet. 

Another possible issue is`@tracked` may not be tracking property changes of objects. E.g. A change to `model.data` to a new array may not trigger a change but a new `model` could.
